name: Update Sprint Planning

on:
  push:
    branches:
      - main

jobs:
  update-sprint-planning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Sprint Planning
        run: |
          TODAY=$(date +'%d-%m-%Y')
          RETROSPECTIVE_FILES=$(find. -type f -name "Sprint-Retrospective-${TODAY}*.md")
          PLANNING_FILE="Sprint-Planning.md"

          echo "# Sprint Planningg" > "$PLANNING_FILE"
          for file in $RETROSPECTIVE_FILES; do
            echo "- [$(basename "$file")]($(dirname "$file")/$(basename "$file"))" >> "$PLANNING_FILE"
          done

      - name: Commit and push changes
        run: |
          git add.
          git commit -m "Update Sprint Planning"
          git push origin main